#Server Setting
server:
  port: 8080
  servlet:
    context-path: /springboot

#Spring Boot Setting
spring:
  #datasource setting
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 546085758
  #hibernate setting
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #Redis Settings
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0
