## 避免和 server 工程端口冲突
server:
  port: 8081

## Dubbo 服务消费者配置
spring:
  dubbo:
    application:
      name: consumer
    registry:
      address: zookeeper://liudeshuai.cn:2181
    protocol:
      host: 127.0.0.1
      name: dubbo
      port: 20880
    scan: bid.adonis.lau.dubbo