## Dubbo 服务提供者配置
spring:
  dubbo:
    application:
      name: provider
    registry:
      address: zookeeper://liudeshuai.cn:2181
    protocol:
      host: 127.0.0.1
      name: dubbo
      port: 20880
    scan: bid.adonis.lau.dubbo