#Server Setting
server:
  servlet:
    context-path: /springboot
  port: 8080

#Spring Boot Setting
spring:
  #datasource setting
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 546085758
  #hibernate setting
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true